### ISSUE TITLE
Low code quality across the entire project

### ISSUE THREAD

**Issue by sorcerer-worker** [foxlldev/Foxlmind#2]
Since not just one, but multiple people reviewing this code found the code quality to be just above spaghetti and just below hell on earth. I largely believe it'd be beneficial to re-factor the whole entire thing as much as possible.

![image](https://user-images.githubusercontent.com/81059531/181049217-81410673-0972-4a76-9cda-36e73aa28a1f.png)

**Comment by foxlldev** [comment]
Right now it works fine, I will probably clean it up at some point. If I do, and I remember, I’ll close this issue and let you know.

**Comment by sorcerer-worker** [comment]
Oh. Really I just opened this out of formality. But alright. Though I still have every intention on slaughtering both issues before you can lift so much as a finger using a pull request.

**Comment by foxlldev** [comment]
You are welcome to.

**Comment by foxlldev** [comment]
Also not completely true, main systems e.g. loading & positing are reasonably well-done.

**Comment by sorcerer-worker** [comment]
For sure! After reading the code for around 2 days I wouldn't say its the worst especially `index.js` it looks really good and clean Foxl! Which is why I also asked for a second opinion from a few developers I know who've coded longer than me to see if they could provide additional feedback on things that'd benefit the project. Given I don't like to judge solely on my own opinion when it comes to things important. It wasn't the most positive, but it was constructive I could show you. But it doesn't matter regardless you put a ton of heart into it! I'm excited for when my PR is fully complete.

**Comment by foxlldev** [comment]
With 0.8.0, we're bringing much higher quality code, inspired by your pull request. Thank you!
