### ISSUE TITLE
Linux not supported

### ISSUE THREAD

**Issue by sorcerer-worker** [foxlldev/Foxlmind#3]
With Linux being such a highly used operating system its kinda crazy Foxlmind only fully supports Windows. I think efforts towards porting it to Linux should be done.

**Comment by foxlldev** [comment]
Right now I’ve been told Electron is a little buggy for Linux. Soon, we will build for it.
Until then, no.

**Comment by foxlldev** [comment]
There are now unofficial builds for Linux available.
Use at your own risk: https://foxlmind-linux.static.app/

**Comment by sorcerer-worker** [comment]
Awesome! More than close enough! Anything for progress! "Use at your own risk" makes me think it'll make the computer explode though. lol
