### ISSUE TITLE
White screen while page updating

### ISSUE THREAD

**Issue by futured-it** [foxlldev/Foxlmind#9]
When you click to any app section that opens a new HTML page, when the page is loading you see the white page. When you use the night theme it's very annoying.
https://www.youtube.com/watch?v=rKqZlEar-gk

**Comment by futured-it** [comment]
This is a minor problem that does not interfere with the use of the program. I will try to fix this problem myself soon. Never mind. This Issue is just there to remind you of its presence.

**Comment by foxlldev** [comment]
yes, this does happen and I will look into fixing it

**Comment by foxlldev** [comment]
i believe this will be fixed in 0.8.0

**Comment by foxlldev** [comment]
Unfixable, unfortunately.
Sorry.
